devices:
  device:
    - type: GroheSense
      todos:
        - name: 'Notifications'
          keypath: 'notifications.notifications'
      sensors:
        - name: 'Temperature'
          keypath: 'details.data_latest.measurement.temperature'
          device_class: 'Temperature'
          unit: 'Celsius'
        - name: 'Humidity'
          keypath: 'details.data_latest.measurement.humidity'
          device_class: 'Humidity'
          unit: 'Percentage'
        - name: 'Battery'
          keypath: 'details.data_latest.measurement.battery'
          device_class: 'Battery'
          unit: 'Percentage'
          category: 'Diagnostic'
        - name: 'Latest notification'
          keypath: 'details.notifications[0]'
          special_type: 'Notification'
    - type: GroheSenseGuard
      todos:
        - name: 'Notifications'
          keypath: 'notifications.notifications'
      valves:
        - name: 'Valve'
          keypath: 'command.valve_open'
          device_class: 'Water'
          features:
            - open
            - close
      sensors:
        - name: 'Temperature'
          keypath: 'details.data_latest.measurement.temperature_guard'
          device_class: 'Temperature'
          unit: 'Celsius'
        - name: 'Water consumption'
          keypath: 'details.data_latest.daily_consumption'
          device_class: 'Water'
          state_class: 'Total Increasing'
          unit: 'Liters'
        - name: 'Average daily consumption'
          keypath: 'details.data_latest.average_daily_consumption'
          device_class: 'Water'
          unit: 'Liters'
        - name: 'Latest consumption'
          keypath: 'details.data_latest.withdrawals.waterconsumption'
          device_class: 'Water'
          unit: 'Liters'
        - name: 'Latest max flow rate'
          keypath: 'details.data_latest.withdrawals.maxflowrate'
          device_class: 'Volume_flow_rate'
          unit: 'Cubic meters'
        - name: 'Average monthly consumption'
          keypath: 'details.data_latest.average_monthly_consumption'
          device_class: 'Water'
          unit: 'Liters'
        - name: 'Actual flow rate'
          keypath: 'details.data_latest.measurement.flowrate'
          device_class: 'Volume_flow_rate'
          unit: 'Cubic meters'
        - name: 'Actual pressure'
          keypath: 'details.data_latest.measurement.pressure'
          device_class: 'Pressure'
          unit: 'Bar'
        - name: 'Latest notification'
          keypath: 'details.notifications[0]'
          special_type: 'Notification'

        - name: 'PM: Pressure drop'
          keypath: 'pressure.items[0].drop_of_pressure'
          device_class: 'Pressure'
          unit: 'Bar'
          enabled: false
          min_version: '3.06'
        - name: 'PM: Is Leakage'
          keypath: 'pressure.items[0].leakage'
          enabled: false
          min_version: '3.06'
        - name: 'PM: Leakage level'
          keypath: 'pressure.items[0].level'
          enabled: false
          min_version: '3.06'
        - name: 'PM: Runtime'
          keypath: 'pressure.items[0].start_time'
          device_class: 'Timestamp'
          enabled: false
          min_version: '3.06'

        - name: 'Snoozed: Until'
          keypath: 'details.snoozed_until'
          device_class: 'Timestamp'
          enabled: false
        - name: 'Snoozed: Status'
          keypath: 'details.snooze_status'
          enabled: false

        - name: 'Update available'
          keypath: 'status.update_available'
          category: 'Diagnostic'
          enabled: false
        - name: 'Wifi quality'
          keypath: 'status.wifi_quality'
          category: 'Diagnostic'
          enabled: false
        - name: 'Online'
          keypath: 'status.connection'
          category: 'Diagnostic'
          enabled: false
    - type: GroheBlueHome
      todos:
        - name: 'Notifications'
          keypath: 'notifications.notifications'
      sensors:
        - name: 'Latest notification'
          keypath: 'details.notifications[0]'
          special_type: 'Notification'

        - name: 'Cycles carbonated'
          keypath: 'details.data_latest.measurement.open_close_cycles_carbonated'
        - name: 'Cycles still'
          keypath: 'details.data_latest.measurement.open_close_cycles_still'

        - name: 'Date cleaning'
          keypath: 'details.data_latest.measurement.date_of_cleaning'
          device_class: 'Timestamp'
        - name: 'Date CO2 replacement'
          keypath: 'details.data_latest.measurement.date_of_co2_replacement'
          device_class: 'Timestamp'
        - name: 'Date Filter replacement'
          keypath: 'details.data_latest.measurement.date_of_filter_replacement'
          device_class: 'Timestamp'

        - name: 'Time idle (max)'
          keypath: 'details.data_latest.measurement.max_idle_time'
          device_class: 'Duration'
          unit: 'Minutes'
        - name: 'Time operating'
          keypath: 'details.data_latest.measurement.operating_time'
          device_class: 'Duration'
          unit: 'Minutes'
        - name: 'Time pump running'
          keypath: 'details.data_latest.measurement.pump_running_time'
          device_class: 'Duration'
          unit: 'Minutes'
        - name: 'Time since last withdrawal'
          keypath: 'details.data_latest.measurement.time_since_last_withdrawal'
          device_class: 'Timestamp'
          special_type: 'Duration as Timestamp'
        - name: 'Water running carbonated'
          keypath: 'details.data_latest.measurement.water_running_time_carbonated'
          device_class: 'Duration'
          unit: 'Minutes'
        - name: 'Water running medium'
          keypath: 'details.data_latest.measurement.water_running_time_medium'
          device_class: 'Duration'
          unit: 'Minutes'
        - name: 'Water running still'
          keypath: 'details.data_latest.measurement.water_running_time_still'
          device_class: 'Duration'
          unit: 'Minutes'

        - name: 'Remaining CO2'
          keypath: 'details.data_latest.measurement.remaining_co2'
          device_class: 'Battery'
          unit: 'Percentage'
        - name: 'Remaining Filter'
          keypath: 'details.data_latest.measurement.remaining_filter'
          device_class: 'Battery'
          unit: 'Percentage'

        - name: 'Remaining CO2 total'
          keypath: 'details.data_latest.measurement.remaining_co2_liters'
          device_class: 'Volume'
          unit: 'Liters'
        - name: 'Remaining Filter total'
          keypath: 'details.data_latest.measurement.remaining_filter_liters'
          device_class: 'Volume'
          unit: 'Liters'

        - name: 'Count cleaning'
          keypath: 'details.data_latest.measurement.cleaning_count'
          category: 'Diagnostic'
          enabled: true
        - name: 'Count filter change'
          keypath: 'details.data_latest.measurement.filter_change_count'
          category: 'Diagnostic'
          enabled: true
        - name: 'Count Power cut'
          keypath: 'details.data_latest.measurement.power_cut_count'
          category: 'Diagnostic'
          enabled: true
        - name: 'Count pump'
          keypath: 'details.data_latest.measurement.pump_count'
          category: 'Diagnostic'
          enabled: true
        - name: 'Time since restart'
          keypath: 'details.data_latest.measurement.time_since_restart'
          device_class: 'Duration'
          unit: 'Minutes'
          category: 'Diagnostic'
        - name: 'Time offset'
          keypath: 'details.data_latest.measurement.timeoffset'
          device_class: 'Duration'
          unit: 'Minutes'
          category: 'Diagnostic'
          enabled: true

        - name: 'Update available'
          keypath: 'status.update_available'
          category: 'Diagnostic'
          enabled: true
        - name: 'Online'
          keypath: 'status.connection'
          category: 'Diagnostic'
          enabled: true

    - type: GroheBlueProf
      todos:
        - name: 'Notifications'
          keypath: 'notifications.notifications'
      sensors:
        - name: 'Latest notification'
          keypath: 'details.notifications[0]'
          special_type: 'Notification'

        - name: 'Cycles carbonated'
          keypath: 'details.data_latest.measurement.open_close_cycles_carbonated'
        - name: 'Cycles still'
          keypath: 'details.data_latest.measurement.open_close_cycles_still'

        - name: 'Date cleaning'
          keypath: 'details.data_latest.measurement.date_of_cleaning'
          device_class: 'Timestamp'
        - name: 'Date CO2 replacement'
          keypath: 'details.data_latest.measurement.date_of_co2_replacement'
          device_class: 'Timestamp'
        - name: 'Date Filter replacement'
          keypath: 'details.data_latest.measurement.date_of_filter_replacement'
          device_class: 'Timestamp'

        - name: 'Time idle (max)'
          keypath: 'details.data_latest.measurement.max_idle_time'
          device_class: 'Duration'
          unit: 'Minutes'
        - name: 'Time operating'
          keypath: 'details.data_latest.measurement.operating_time'
          device_class: 'Duration'
          unit: 'Minutes'
        - name: 'Time pump running'
          keypath: 'details.data_latest.measurement.pump_running_time'
          device_class: 'Duration'
          unit: 'Minutes'
        - name: 'Time since last withdrawal'
          keypath: 'details.data_latest.measurement.time_since_last_withdrawal'
          device_class: 'Timestamp'
          special_type: 'Duration as Timestamp'
        - name: 'Water running carbonated'
          keypath: 'details.data_latest.measurement.water_running_time_carbonated'
          device_class: 'Duration'
          unit: 'Minutes'
        - name: 'Water running medium'
          keypath: 'details.data_latest.measurement.water_running_time_medium'
          device_class: 'Duration'
          unit: 'Minutes'
        - name: 'Water running still'
          keypath: 'details.data_latest.measurement.water_running_time_still'
          device_class: 'Duration'
          unit: 'Minutes'

        - name: 'Remaining CO2'
          keypath: 'details.data_latest.measurement.remaining_co2'
          device_class: 'Battery'
          unit: 'Percentage'
        - name: 'Remaining Filter'
          keypath: 'details.data_latest.measurement.remaining_filter'
          device_class: 'Battery'
          unit: 'Percentage'

        - name: 'Remaining CO2 total'
          keypath: 'details.data_latest.measurement.remaining_co2_liters'
          device_class: 'Volume'
          unit: 'Liters'
        - name: 'Remaining Filter total'
          keypath: 'details.data_latest.measurement.remaining_filter_liters'
          device_class: 'Volume'
          unit: 'Liters'

        - name: 'Count cleaning'
          keypath: 'details.data_latest.measurement.cleaning_count'
          category: 'Diagnostic'
          enabled: true
        - name: 'Count filter change'
          keypath: 'details.data_latest.measurement.filter_change_count'
          category: 'Diagnostic'
          enabled: true
        - name: 'Count Power cut'
          keypath: 'details.data_latest.measurement.power_cut_count'
          category: 'Diagnostic'
          enabled: true
        - name: 'Count pump'
          keypath: 'details.data_latest.measurement.pump_count'
          category: 'Diagnostic'
          enabled: true
        - name: 'Time since restart'
          keypath: 'details.data_latest.measurement.time_since_restart'
          device_class: 'Duration'
          unit: 'Minutes'
          category: 'Diagnostic'
        - name: 'Time offset'
          keypath: 'details.data_latest.measurement.timeoffset'
          device_class: 'Duration'
          unit: 'Minutes'
          category: 'Diagnostic'
          enabled: true

        - name: 'Update available'
          keypath: 'status.update_available'
          category: 'Diagnostic'
          enabled: true
        - name: 'Online'
          keypath: 'status.connection'
          category: 'Diagnostic'
          enabled: true

